### ISSUE TITLE
Hi, I have a similar project and have completed 1/4.

### ISSUE THREAD

**Issue by guonaihong** [aporcupine/GoUnix#5]
I want everyone to complete this project together. If I am alone, I may have to finish it all in June.
```
Https://github.com/guonaihong/coreutils
```

**Comment by aporcupine** [comment]
This project is more of a learning exercise than a full implementation of coreutils. I hope to get a number of different examples from different people, to allow everyone to compare their implementation with others.

If you wanted to add some of yours here as well as your project (for other people to learn from) feel free to send a pull request. :)
